---
galaxy_info:
  author: Tony Reveal <https://github.com/tonyreveal>
  description: Perform controlled RouterOS maintenance actions.
  license: GPL-3.0-or-later
  min_ansible_version: '2.16'
  galaxy_tags:
    - routeros
    - mikrotik
    - network
dependencies: []
...
