---
- name: Validate baseline settings
  ansible.builtin.assert:
    that:
      - routeros_baseline_identity is mapping
    fail_msg: Baseline identity settings must be a mapping.

- name: Configure RouterOS identity
  changed_when: true
  when: routeros_baseline_identity.name is defined
  community.routeros.command:
    commands:
      - "/system identity set name={{ routeros_baseline_identity.name }}"

...
