---
- name: Validate OSPF instances
  ansible.builtin.assert:
    that:
      - routeros_ospf_instances is sequence
      - routeros_ospf_instances | selectattr('name', 'defined') | list | length == routeros_ospf_instances | length
    fail_msg: OSPF instances require name.

- name: Configure RouterOS OSPF instances
  loop: "{{ routeros_ospf_instances }}"
  loop_control:
    label: "{{ item.name }}"
  changed_when: true
  when: routeros_ospf_instances | length > 0
  community.routeros.command:
    commands:
      - >-
        /routing ospf instance add name={{ item.name }}{% for option in item.options | default({}) | dict2items %} {{ option.key }}={{ option.value }}{% endfor %}
...
